# Playbook de configuração pós formatação do notebook utilizando Linux Mint 19 XFCE

---
- hosts: all
  gather_facts: true
 
  vars:
   usuario: sergei

  tasks:
    - name: ADICIONANDO | Repositorio Numix
      raw: apt-add-repository ppa:numix/ppa -y

    - name: ADICIONANDO | Repositorio Tilix
      raw: add-apt-repository ppa:webupd8team/terminix -y 

    - name: ADICIONANDO | Repositorio MPlayer
      raw: add-apt-repository ppa:mc3man/mpv-tests -y
  
    - name: ADICIONANDO | Repositorio Notepadqq
      raw: add-apt-repository ppa:notepadqq-team/notepadqq -y
      
    - name: ATUALIZANDO | Sourcelist 
      apt: 
        update_cache: yes
   
    - name: ADICIONANDO | Chave para instalacao do Google Chrome
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

    - name: ADICIONANDO | Repositorio Google Chrome
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        update_cache: yes

    - name: INSTALANDO | Google Chorme Stable
      apt:
        name: google-chrome-stable
        state: present

    - name: INSTALANDO | Pacotes Rede
      apt: name={{ item }} state=present
      with_items:
        - atop
        - freerdp-x11
        - gufw
        - htop
        - iotop
        - iptraf-ng
        - nmap
        - openssh-server
        - pptpd
        - remmina
        - remmina-plugin-rdp
        - rsync
        - tcpdump
        - traceroute
        - wireshark

    - name: INSTALANDO | Pacotes Multimidia
      apt: name={{ item }} state=present
      with_items:
        - audacious
        - ffmpeg
        - lynx
        - moc
        - picard
        - vlc
        - xboxdrv
        - youtube-dl
    
    - name: INSTALANDO | Pacotes Codecs
      apt: name={{ item }} state=present
      with_items:
        - ubuntu-restricted-extras 
        - ubuntu-restricted-addons
        - libavcodec-extra 
        - libavcodec-extra
   
    - name: INSTALANDO | Pacotes basicos
      apt: name={{ item }} state=present
      with_items:
        - baobab
        - bc
        - calibre
        - cmatrix
        - cowsay
        - cups-pdf
        - curl
        - docky
        - gedit
        - git
        - gnome-system-monitor
        - gsmartcontrol
        - keepass2
        - inxi
        - linux-firmware
        - luckybackup
        - mono-complete
        - mousepad
        - redshift
        - redshift-gtk
        - screenfetch
        - synapse
        - sysstat
        - trash-cli
        - tree
        - ttf-mscorefonts-installer
        - usb-creator-gtk
        - variety
        - vim
        - xbacklight
        - xfce4-goodies
#        - gns3 # Nao utilizado mais
#        - task # Nao encontrado na versao do Ubuntu 18.04 
   
    - name: INSTALANDO | Temas Numix
      apt: name={{ item }} state=present
      with_items:
        - numix-icon-theme
        - numix-icon-theme-circle

    - name: INSTALANDO | Tilix
      apt: name={{ item }} state=present
      with_items:
        - tilix

    - name: INSTALANDO | Notepadqq
      apt: name={{ item }} state=present
      with_items:
        - notepadqq
    
    - name: INSTALANDO | MPlayer
      apt: name={{ item }} state=present
      with_items:
        - mpv

    - name: CONFIGURANDO | Logs systemctl permanente
      replace:
        path: /etc/systemd/journald.conf
        regexp: '^#Storage=auto'
        replace: 'Storage=persistent'
        
    - name: CONFIGURANDO | Teclado em Ingles do Dell 7567
      copy:
        src: configuracoes/keyboard
        dest: /etc/default
#        mode: 0755
    
    - name: CONFIGURANDO | Pacotes recomendados
      replace:
        path: /etc/apt/apt.conf.d/00recommends
        regexp: '"false"'
        replace: '"true"'
    
    - name: CONFIGURANDO | Utilização de swap
      lineinfile:
        path: /etc/sysctl.conf
        line: "vm.swappiness=10"

#    - name: VALIDANDO | Se hibernacao esta ativa
#      stat: path=Configurando 
#      register: hibernacao

#    - name: CONFIGURANDO | Desativando Hibernação
#      raw: mv -v /etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla /
#      when: hibernacao.stat.exists

    - name: CONFIGURANDO | Desativando touchpad P1
      file:
        path: /etc/udev/rules.d/01-touchpad.rules
        state: touch
        mode: 0755

    - name: CONFIGURANDO | Desativando touchpad P2
      blockinfile:
        path: /etc/udev/rules.d/01-touchpad.rules
        block: |
          SUBSYSTEM=="input", KERNEL=="mouse[0-9]*", ACTION=="add", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/{{ usuario }}/.Xauthority", RUN+="/usr/bin/synclient TouchpadOff=1"
          SUBSYSTEM=="input", KERNEL=="mouse[0-9]*", ACTION=="remove", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/{{ usuario }}/.Xauthority", RUN+="/usr/bin/synclient TouchpadOff=0"
   
    - name: CONFIGURANDO | Git e Tilix 
      blockinfile:
        path: /home/{{ usuario }}/.bashrc
        block: |
          if [ -f ~/.devpreferences ]; then
             . ~/.devpreferences
          fi

     # https://gnunn1.github.io/tilix-web/manual/vteconfig/
    - name: CONFIGURANDO | link simbolico Tilix
      file:
        src: /etc/profile.d/vte-2.91.sh
        dest: /etc/profile.d/vte.sh
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
        state: link

    - name: CONFIGURANDO | Copiando preferencias de Dev
      copy:
        src: configuracoes/.devpreferences
        dest: /home/{{ usuario }}

#    - name: CONFIGURANDO | Desativando Apparmor
#      raw: systemctl disable apparmor.service

    - name: ATUALIZANDO | Upgrade de todos os pacotes
      apt: 
        update_cache: yes
        upgrade: full



